<a href="https://colab.research.google.com/github/Pakhi27/FakeNewsClassifier-LSTM/blob/main/FakeNewsClassifier_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

In [14]:
def handle_bad_line(line):
    print(f"Bad line: {line}")
    return None  # or return the line modified to fit the expected format

df = pd.read_csv('train.csv', delimiter=',', encoding='utf-8', on_bad_lines=handle_bad_line, engine='python')



In [15]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [16]:
df.shape

(6434, 5)

In [17]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [18]:
df.isnull().sum()

id          0
title     178
author    619
text       13
label       0
dtype: int64

In [19]:
###Drop Nan Values
df=df.dropna()

In [26]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [20]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [21]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [22]:
## Get the Dependent features
y=df['label']

In [23]:
X.shape

(5637, 4)

In [24]:
y.shape

(5637,)

In [27]:
import tensorflow as tf

In [28]:
tf.__version__

'2.17.0'

In [29]:
from tensorflow.keras.layers import Embedding# word 2 vec
from tensorflow.keras.preprocessing.sequence import pad_sequences# pre-padding and post padding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [30]:
### Vocabulary size
voc_size=5000

In [ ]:
# One Hot representation

In [31]:
messages=X.copy()

In [32]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [33]:
messages

id                                              title  \
0        0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1        1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2        2                  Why the Truth Might Get You Fired   
3        3  15 Civilians Killed In Single US Airstrike Hav...   
4        4  Iranian woman jailed for fictional unpublished...   
...    ...                                                ...   
6429  6429  Moveable Feast Cafe 2016/10/28 … Open Thread |...   
6430  6430  Hajj Prep: Search Soul, Buy Sturdy Shoes, Pay ...   
6431  6431  10 radikale Vorhaben, die Donald Trump sofort ...   
6432  6432                               Little Blue Balls...   
6433  6433  WATCH: Louis CK’s EPIC Answer on Trump vs. Hil...   

                                   author  \
0                           Darrell Lucus   
1                         Daniel J. Flynn   
2                      Consortiumnews.com   
3                         Jessica Purkiss   
4                          Howard Portnoy   
...                                   ...   
6429                         Herb Swanson   
6430                           Diaa Hadid   
6431  noreply@blogger.com (Der Postillon)   
6432                              recrisp   
6433                          Grant Stern   

                                                   text  
0     House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Ever get the feeling your life circles the rou...  
2     Why the Truth Might Get You Fired October 29, ...  
3     Videos 15 Civilians Killed In Single US Airstr...  
4     Print \nAn Iranian woman has been sentenced to...  
...                                                 ...  
6429  Leave a Reply Click here to get more info on f...  
6430  JIDDA, Saudi Arabia  —   My father was on the ...  
6431  Donnerstag, 10. November 2016 10 radikale Vorh...  
6432  link Years ago I came here for the UFOs and af...  
6433  Comments \nConan O’Brien asked comedian Louis ...  

[5637 rows x 4 columns]

In [34]:
messages.reset_index(inplace=True)

In [35]:
messages

index    id                                              title  \
0         0     0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1         1     1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2         2     2                  Why the Truth Might Get You Fired   
3         3     3  15 Civilians Killed In Single US Airstrike Hav...   
4         4     4  Iranian woman jailed for fictional unpublished...   
...     ...   ...                                                ...   
5632   6429  6429  Moveable Feast Cafe 2016/10/28 … Open Thread |...   
5633   6430  6430  Hajj Prep: Search Soul, Buy Sturdy Shoes, Pay ...   
5634   6431  6431  10 radikale Vorhaben, die Donald Trump sofort ...   
5635   6432  6432                               Little Blue Balls...   
5636   6433  6433  WATCH: Louis CK’s EPIC Answer on Trump vs. Hil...   

                                   author  \
0                           Darrell Lucus   
1                         Daniel J. Flynn   
2                      Consortiumnews.com   
3                         Jessica Purkiss   
4                          Howard Portnoy   
...                                   ...   
5632                         Herb Swanson   
5633                           Diaa Hadid   
5634  noreply@blogger.com (Der Postillon)   
5635                              recrisp   
5636                          Grant Stern   

                                                   text  
0     House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Ever get the feeling your life circles the rou...  
2     Why the Truth Might Get You Fired October 29, ...  
3     Videos 15 Civilians Killed In Single US Airstr...  
4     Print \nAn Iranian woman has been sentenced to...  
...                                                 ...  
5632  Leave a Reply Click here to get more info on f...  
5633  JIDDA, Saudi Arabia  —   My father was on the ...  
5634  Donnerstag, 10. November 2016 10 radikale Vorh...  
5635  link Years ago I came here for the UFOs and af...  
5636  Comments \nConan O’Brien asked comedian Louis ...  

[5637 rows x 5 columns]

In [36]:
import nltk
import re
from nltk.corpus import stopwords

In [37]:
# stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [38]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    # removing special characters and replacing it with blanks
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [39]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [40]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [41]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2617, 592, 1550, 2467, 4344, 1760, 787, 2328, 2101, 125],
 [336, 4764, 1463, 2860, 2323, 1124, 4674],
 [1288, 283, 1892, 2964],
 [4580, 4683, 3914, 1222, 4444, 4346],
 [1908, 2323, 2557, 3603, 3909, 3650, 2323, 822, 1205, 4262],
 [3004,
  1355,
  2670,
  2325,
  4937,
  4786,
  1968,
  4040,
  3556,
  4438,
  2767,
  4326,
  301,
  3503,
  4674],
 [2135, 4931, 161, 12, 3731, 1270, 2229, 4234, 4724, 4304, 3076],
 [3112, 753, 1120, 1854, 400, 2552, 4786, 4791, 4724, 4304, 3076],
 [4394, 2749, 2633, 3141, 2572, 4392, 369, 148, 4786, 3214],
 [843, 1654, 581, 579, 3694, 1452, 2380, 3383],
 [382, 858, 4907, 710, 2119, 2854, 878, 3490, 1055, 4940, 4652],
 [1222, 4766, 4344, 4392, 4786, 400],
 [2347, 1244, 3408, 2557, 2154, 3129, 4136, 1440, 2959],
 [4594, 2380, 2531, 307, 3372, 3910, 894, 4724, 4304, 3076],
 [2427, 1650, 193, 4453, 1276, 4724, 4304, 3076],
 [3238, 1159, 372, 3654, 4808, 3737, 3959, 3656, 3034, 3902],
 [4101, 561, 4764],
 [1101, 2491, 1640, 4264, 4786, 2716, 3504, 4674],
 [4

In [42]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [43]:
onehot_repr[1]

[336, 4764, 1463, 2860, 2323, 1124, 4674]

In [ ]:
# Embedding representation

In [44]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[2617  592 1550 ...    0    0    0]
 [ 336 4764 1463 ...    0    0    0]
 [1288  283 1892 ...    0    0    0]
 ...
 [2548 1956 3215 ...    0    0    0]
 [ 558  224 2640 ...    0    0    0]
 [4421 3311 1680 ...    0    0    0]]


In [45]:
embedded_docs[1]

array([ 336, 4764, 1463, 2860, 2323, 1124, 4674,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [46]:
embedded_docs[0]

array([2617,  592, 1550, 2467, 4344, 1760,  787, 2328, 2101,  125,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [47]:
## Creating model
# each and every word is going to get converted into a vector of 40 size
embedding_vector_features=40 ##features representation
model=Sequential()

# embedding layer
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

# LSTM-100 NEURONS
model.add(LSTM(100))

# Sigmoid for binary prediction in model
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [48]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Assuming voc_size and sent_length are predefined variables
embedding_vector_features = 40  # Size of the embedding vector

model = Sequential()

# Embedding layer with correct input_dim (voc_size) and without deprecated input_length
model.add(Embedding(input_dim=voc_size, output_dim=embedding_vector_features))

# LSTM layer
model.add(LSTM(100))

# Dense layer with sigmoid activation for binary classification
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Display the model summary
print(model.summary())


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [49]:
model.build(input_shape=(None, sent_length))


In [50]:
import numpy as np

# Dummy data: batch size of 1, sentence length of sent_length
dummy_input = np.random.randint(0, voc_size, (1, sent_length))
model.predict(dummy_input)

print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 20, 40)              │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [51]:
len(embedded_docs),y.shape

(5637, (5637,))

In [52]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [53]:
X_final.shape,y_final.shape

((5637, 20), (5637,))

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
# Model Training

In [56]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 6s 46ms/step - accuracy: 0.6378 - loss: 0.5923 - val_accuracy: 0.8925 - val_loss: 0.2592
Epoch 2/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - accuracy: 0.9363 - loss: 0.1700 - val_accuracy: 0.9087 - val_loss: 0.2149
Epoch 3/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9786 - loss: 0.0735 - val_accuracy: 0.9044 - val_loss: 0.2707
Epoch 4/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 0.9940 - loss: 0.0383 - val_accuracy: 0.9070 - val_loss: 0.2982
Epoch 5/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 4s 62ms/step - accuracy: 0.9948 - loss: 0.0226 - val_accuracy: 0.9033 - val_loss: 0.3701
Epoch 6/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9978 - loss: 0.0093 - val_accuracy: 0.8968 - val_loss: 0.4162
Epoch 7/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.9985 - loss: 0.0090 - val_accuracy: 0.9033 - val_loss: 0.4364
Epoch 8/10
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9995 - loss: 0.0044 - val_accuracy: 0.9006 - v

In [ ]:
# Performance Metrics & Accuracy

In [57]:
y_pred=model.predict(X_test)

59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step


In [63]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [64]:
# setting a threshold value of 0.5->0.5=1 and <0.5 =0
from sklearn.metrics import confusion_matrix

In [65]:
confusion_matrix(y_test,y_pred)

array([[989,  68],
       [139, 665]])

In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
#88%

0.8887694787748522

In [67]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      1057
           1       0.91      0.83      0.87       804

    accuracy                           0.89      1861
   macro avg       0.89      0.88      0.89      1861
weighted avg       0.89      0.89      0.89      1861

